version: 0.1.4
slug: silabs_concurrent_multiprotocol
name: Silicon Labs Concurrent Multiprotocol
description: Zigbee NCP and OpenThread multiprotocol add-on
url: https://github.com/home-assistant/addons-development/tree/master/silabs-concurrent-multiprotocol
arch:
  - armv7
  - aarch64
  - amd64
hassio_api: true
# IPC is only used within the Add-on
host_ipc: false
host_network: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
image: homeassistant/{arch}-addon-silabs-concurrent-multiprotocol
init: false
options:
  device: null
  baudrate: 230400
  flow_control: true
  cpcd_trace: false
  otbr_enable: true
  otbr_debug: false
  firewall: true
ports:
  9999/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
schema:
  device: device(subsystem=tty)?
  baudrate: list(57600|115200|230400|460800|921600)?
  flow_control: bool?
  network_device: str?
  cpcd_trace: bool
  otbr_enable: bool
  otbr_debug: bool
  firewall: bool
stage: experimental
startup: services
ingress: true
ingress_port: 8080
panel_title: OpenThread
panel_icon: mdi:view-grid-plus-outline
panel_admin: true
