build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.18
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
