build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.10-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16
