name: Custom deps deployment
init: false
version: 1.3.4
slug: custom_deps
description: Manage custom Python modules in Home Assistant deps
url: https://github.com/home-assistant/addons-development
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: once
advanced: true
homeassistant: 2021.7.0
stage: experimental
boot: manual
map:
- config:rw
options:
  pypi:
  -
  apk: []
schema:
  pypi:
  - str
  apk:
  - str
image: homeassistant/{arch}-addon-dev-custom_deps
