build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.17
  amd64: ghcr.io/home-assistant/amd64-base:3.17
  armhf: ghcr.io/home-assistant/armhf-base:3.17
  armv7: ghcr.io/home-assistant/armv7-base:3.17
  i386: ghcr.io/home-assistant/i386-base:3.17
args:
  LIBWEBSOCKETS_VERSION: 4.3.2
  TTYD_VERSION: 1.7.3
