build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
args:
  CHIP_VERSION: 5d8599d195a93dfe5473f64e4f888c322e5df1d2
  MATTER_SERVER_VERSION: 0.2.1
