build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  LIBWEBSOCKETS_VERSION: 4.3.5
  TTYD_VERSION: 1.7.7
  CHIP_VERSION: v1.4.2.0
