build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  i386: ghcr.io/home-assistant/i386-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
  armhf: ghcr.io/home-assistant/armhf-base-debian:bookworm
args:
  CP210X_CFG_COMMIT: b417a28b3367a65990ad501c6cb98da2c32b7ea4