---
version: 1.0.0
name: SkyConnect CP2102N Programmer
slug: skyconnect-cp2102n-programmer
description: Program the manufacturer and vendor strings to a SkyConnect's CP2102N chip
url: "https://github.com/home-assistant/addons-development/tree/master/skyconnect-cp2102n-programmer"
image: homeassistant/{arch}-addon-skyconnect-cp2102n-programmer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: experimental
startup: once
boot: manual
hassio_api: true
init: false
usb: true
options:
  device: null
  advanced:
    manufacturer: "Nabu Casa"
    product: "SkyConnect v1.0"
schema:
  device: device(subsystem=tty)
  advanced:
    manufacturer: str
    product: str